version: '3.8'

services:
    react-app:
        image: react-app
        build:
            context: .
            dockerfile: ./Dockerfile
        command: yarn start
        ports:
            - 3000:3000
        volumes:
            - .:/app/node_modules